language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS=-Xmx2048m -Dorg.gradle.parallel=false
    # COMPONENT_GOOGLE_REPO
    - secure: "OQ/wkORxY2qv4CmAdMxyW4ihRt5GRyxKxQRZpsdjMbwIKf3DlY6vBoNIEQ46sRRLAKOzkQ3LirodbWRCBlDN9WFw4XRsLTveqqtslMGeLf04peazXMIa6rJ22BCDGEmnzRNx6r3JRb9wEK1plNv4u4G9DgQ7ShzbwdZ8A5grlg8="

addons:
  apt:
    packages:
      - tar
      - gzip
      - patch
      - openssh-client
      - git

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/

before_install:
  - openssl aes-256-cbc -K $encrypted_9b8203f9524d_key -iv $encrypted_9b8203f9524d_iv -in travis/configs/twidere_private_config.tar.gz.enc -out travis/configs/twidere_private_config.tar.gz -d

install:
  # Extracts build configs into source tree
  - tar zxf travis/configs/twidere_private_config.tar.gz
  # Make sure ~/.ssh/ exists
  - mkdir -p ~/.ssh/
  # Make it secure
  - chmod 700 ~/.ssh/
  # Append ssh_config
  - cat private/ssh_config >> ~/.ssh/config
  # Append known_hosts
  - cat private/ssh_known_hosts >> ~/.ssh/known_hosts
  # Checkout Google components
  - ssh-agent bash -c "ssh-add private/ssh_id_rsa; git clone $COMPONENT_GOOGLE_REPO twidere/src/google" > /dev/null 2>&1

before_script:
  # Validate if patches work
  - patch --dry-run -d twidere < twidere/patches/remove_closed_source_dependencies.patch
  # Validate if Google components fetched successfully
  - test -f twidere/src/google/AndroidManifest.xml

script: ./gradlew build --no-daemon --stacktrace

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: "WKtKwda3hegqO9QVujdonNoL2ESJUR80WHNq/13wDsbCABo/GNnuqHNYZmml3wAifEKKeCEYfNZRUuHQ8eHs54Lj5BlGRX5i+1LrGhhgnVFQgmrhIv4RJuVQ663kDEh+Jwo4vowJ2mxNDvLvOhfZwxjULPDiknqy6u5PyW3id5M="
  file_glob: true
  file: '**/*-release.apk'
  on:
    repo: TwidereProject/Twidere-Android
    tags: true