language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx1024m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - python2.7
      - libmagic1
      - patch

#cache:
#  directories:
#  - $HOME/.local/opt

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - openssl aes-256-cbc -K $encrypted_9b8203f9524d_key -iv $encrypted_9b8203f9524d_iv -in travis/configs/twidere_private_config.tar.gz.enc -out travis/configs/twidere_private_config.tar.gz -d

before_script:
  # Extracts build configs into source tree
  - tar zxf travis/configs/twidere_private_config.tar.gz
  # Validate if patches work
  - patch --dry-run -d twidere < twidere/patches/remove_closed_source_dependencies.patch

script: ./gradlew build --no-daemon --stacktrace
